GET {{host}}/app/v1/health-check

###

POST {{host}}/app/v1/task/create
Content-Type: application/json

{
  "flow": "test",
  "arguments": {
    "order_id": "000001",
    "product": "check+",
    "itn": "3000000000",
    "phone": "380505555555",
    "value": 12345,
    "length": 12,
    "decision": "rejected"
  }
}